/**
 * Application Error Codes
 *
 * Central registry of stable, machine-readable error codes.
 * Used by GlobalExceptionFilter to map exceptions to standardized responses.
 */

export const AppErrorCodes = {
  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_FIELD_INVALID: 'VALIDATION_FIELD_INVALID',
  VALIDATION_FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_STALE_TOKEN: 'AUTH_STALE_TOKEN',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_PASSWORD_RECOVERY_DISABLED: 'AUTH_PASSWORD_RECOVERY_DISABLED',
  AUTH_PASSWORD_RECOVERY_INVALID_OR_EXPIRED: 'AUTH_PASSWORD_RECOVERY_INVALID_OR_EXPIRED',

  // RBAC
  RBAC_ACCESS_DENIED: 'RBAC_ACCESS_DENIED',
  RBAC_ROUTE_UNCLASSIFIED: 'RBAC_ROUTE_UNCLASSIFIED',
  RBAC_MISSING_PERMISSION: 'RBAC_MISSING_PERMISSION',

  // Database
  DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DB_FOREIGN_KEY_CONSTRAINT: 'DB_FOREIGN_KEY_CONSTRAINT',
  DB_INVALID_QUERY: 'DB_INVALID_QUERY',
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_TRANSACTION_ERROR: 'DB_TRANSACTION_ERROR',
} as const;

export type AppErrorCode = (typeof AppErrorCodes)[keyof typeof AppErrorCodes];